# Generated by Django 3.0.1 on 2019-12-28 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_cha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yxh', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=128)),
                ('xm', models.CharField(max_length=128)),
                ('xb', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('csrq', models.CharField(max_length=128)),
                ('jg', models.CharField(max_length=128)),
                ('sjhm', models.CharField(max_length=128)),
                ('yxh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Department')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gh', models.CharField(max_length=128)),
                ('xm', models.CharField(max_length=128)),
                ('xb', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('csrq', models.CharField(max_length=128)),
                ('xl', models.CharField(max_length=128)),
                ('jbgz', models.IntegerField(max_length=32)),
                ('yxh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Department')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
