# Generated by Django 3.0.1 on 2019-12-28 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191228_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='csrq',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='jg',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sjhm',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='csrq',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='xl',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
