# Generated by Django 3.0.1 on 2019-12-28 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191228_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='csrq',
            field=models.CharField(max_length=128, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='jg',
            field=models.CharField(max_length=128, null=True, verbose_name='籍贯'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sjhm',
            field=models.CharField(max_length=128, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='xb',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='xh',
            field=models.CharField(max_length=128, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='xm',
            field=models.CharField(max_length=128, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='yxh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Department', verbose_name='院系号'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gh',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
