# Generated by Django 3.0.1 on 2019-12-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20191229_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='csrq',
            field=models.CharField(max_length=128, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gh',
            field=models.CharField(max_length=128, unique=True, verbose_name='工号'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='jbgz',
            field=models.IntegerField(verbose_name='基本工资'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='xb',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='xl',
            field=models.CharField(max_length=128, null=True, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='xm',
            field=models.CharField(max_length=128, verbose_name='姓名'),
        ),
    ]
