# Generated by Django 3.0.1 on 2019-12-29 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20191229_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kh', models.CharField(max_length=128, unique=True, verbose_name='课号')),
                ('km', models.CharField(max_length=128, verbose_name='课名')),
                ('xf', models.IntegerField(verbose_name='学分')),
                ('xs', models.IntegerField(verbose_name='学时')),
                ('yxh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Department', verbose_name='院系号')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='OpenCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=128, verbose_name='学期')),
                ('sksj', models.CharField(max_length=128, verbose_name='上课时间')),
                ('gh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Teacher', verbose_name='工号')),
                ('kh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Course', verbose_name='课号')),
            ],
            options={
                'verbose_name': '开课',
                'verbose_name_plural': '开课',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=128, verbose_name='学期')),
                ('pscj', models.IntegerField(null=True, verbose_name='平时成绩')),
                ('kscj', models.IntegerField(null=True, verbose_name='考试成绩')),
                ('zpcj', models.IntegerField(null=True, verbose_name='总评成绩')),
                ('gh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Teacher', verbose_name='工号')),
                ('kh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Course', verbose_name='课号')),
                ('xh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Student', verbose_name='学号')),
            ],
            options={
                'verbose_name': '选课',
                'verbose_name_plural': '选课',
            },
        ),
    ]
