# Generated by Django 3.0.1 on 2019-12-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_course_event_opencourse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('xh', 'xq', 'kh', 'gh')},
        ),
        migrations.AlterUniqueTogether(
            name='opencourse',
            unique_together={('xq', 'kh', 'gh')},
        ),
    ]
