# Generated by Django 3.0.1 on 2019-12-30 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20191229_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='yxh',
            new_name='depart',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='kh',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='xh',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='gh',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='opencourse',
            old_name='kh',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='opencourse',
            old_name='gh',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='yxh',
            new_name='depart',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='yxh',
            new_name='depart',
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('student', 'xq', 'lesson', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='opencourse',
            unique_together={('xq', 'lesson', 'teacher')},
        ),
    ]
