# Generated by Django 3.0.1 on 2019-12-30 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20191230_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='event',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Student', verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='event',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Teacher', verbose_name='教师'),
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Teacher', verbose_name='教师'),
        ),
    ]
