# Generated by Django 3.0.1 on 2019-12-30 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20191230_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.OpenCourse', verbose_name='课程'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('student', 'lesson', 'teacher')},
        ),
        migrations.RemoveField(
            model_name='event',
            name='xq',
        ),
    ]
