# Generated by Django 2.2.9 on 2020-03-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20191230_2128'),
    ]

    operations = [
    ]
