# Generated by Django 2.2.9 on 2020-03-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20200306_1654'),
    ]

    operations = [
    ]
