# Generated by Django 2.2.9 on 2020-03-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20200306_1655'),
    ]

    operations = [
    ]
