# Generated by Django 2.2.9 on 2020-03-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20200306_1658'),
    ]

    operations = [
    ]
